services:
  gomft:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gomft
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      # Main data directory - contains DB and configs
      - gomft-data:/app/data
      # Separate backups directory
      - gomft-backups:/app/backups
      # For development, you can mount the source code
      # - .:/app
    environment:
      - TZ=UTC
      - DATA_DIR=/app/data
      - BACKUP_DIR=/app/backups
      - LOGS_DIR=/app/data/logs
      # - LOG_LEVEL=info
    networks:
      - gomft-network

networks:
  gomft-network:
    driver: bridge

volumes:
  gomft-data:
    driver: local
  gomft-backups:
    driver: local 